### ISSUE TITLE
About

### ISSUE THREAD

**Issue by YCF** [YCF/ycf.github.com#1]
### 关于我

我不叫程旭媛，也不是程序猿，是太差了公司的一名闲杂员工，修电脑是主要业务。日常使用 Flask（Python 2.7 ） 在 Windows（对，你没看错，就这个傻X ） 下开发一些所谓的 Web APP，我是一个全端工程狮，专门填坑的。目前在入门 Golang 和对 JavaScript 进行进一步了解（不敢说懂啊，js太多坑了）。
### 联系我

建议直接在 Github 留言，或使用下面的邮箱，可能回复相当不及时，请谅解。

> ZW5qb3lmb3JmdW5AZ21haWwuY29t (BASE64)

当然，如果你也在 [V2EX](https://v2ex.com/) 混，请 [@loading](https://v2ex.com/member/loading) 。
### 业余爱好

上学的时候是遥控模型，玩的是 1/10 电动房车，拿过不少奖。最近喜欢上了自行车这项运动，购入了鱼总那里的风行 412 (齿比 9:45)。下班后一周会跑几次步，一般是速度较快地跑 3km。
### 电子设备
-   ~~Nexus 5~~ => [Mi Max](http://www.mi.com/mimax/)
-   Thinkpad x220 with SSD & 8G ram
-   Macbook Air 11' with 8G ram
-   Nintendo New 3DS LL (Big fan of Master Hunter )
### Linux 黑历史

知道 Linux 很久，使用过不少版本，虽然没什么惊人的成就，但如果在简历上，我还是敢写上“折腾过 Linux”。

版本变迁（大概）：

> RH 7.1 > 红旗 > 蓝点 > Mandriva 2004 > Debian (gnome) > Ubuntu (compiz，rox-desktop，尝试各种衍生，最惊艳 elementary OS)> Gentoo (openbox) > Archlinux (awesome+dzen2)

_印象最深的App是 rox，因为它还能当 wm，而且速度非常非常非常快~_
### 关于使用 Github issues 写作

第一次知道可以用 issues 写博客都不知道是什么时候了，现在正式加入到 issues 大军中。

写作场景主要有下面两个：
1.  使用 Github 官方的 Android 客户端在手机或平板上写。
2.  使用 [Medium Editor Markdown](http://ionicabizau.github.io/medium-editor-markdown/) 在 Firefox 上写，这是一个在 Medium 官方编辑器基础上加入 Markdown 支持的编辑器，界面简洁，符合我的审美 。Github：[medium-editor-markdown](https://github.com/IonicaBizau/medium-editor-markdown)

**Comment by qinjinling** [comment]
牛掰:)
