### ISSUE TITLE
golang

### ISSUE THREAD

**Issue by YCF** [YCF/ycf.github.com#11]
### 选择理由
1. [优酷:Let it go](http://v.youku.com/v_show/id_XODE4MTM2MjQ4.html?from=s1.8-1-1.2)
### 教程
1. [Go 边看边练 -《Go 学习笔记》系列](http://symphony.b3log.org/tags/Go%20%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0)

如果需要像 windows 里 ini 的配置文件，使用 toml 。

**Comment by saltbo** [comment]
Write in go, 简直了
