### ISSUE TITLE
对 Surface 4 长草了

### ISSUE THREAD

**Issue by YCF** [YCF/ycf.github.com#23]
因为日常使用传统笔记本感觉不太方便，所以就又产生了购买一台生产力电子设备的想法。
目前手里笔记本有 Macbook Air 11 和 Thinkpad x220 ，还有一台 iPad mini ，通过日常使用基本已经可以否定购买 Macbook 和 iPad 的任何系列硬件产品的想法了。
经过对 OS 需求分析：
1. 目前没有搭载 OS X 系统的硬件。
2. 搭载 Linux 系统的，我觉得还不如买安卓大平板，因为前期已经入手过 Nexus 7 加上目前使用的是屏幕尺寸有 6.4 寸小米 Max （这篇文章就是使用小米 Max + Poker 撰写的）
3. 最后也就只能剩下 windows 可选！

然后，自然就是 Surface 系列。由于对屏幕尺寸有自己的特殊爱好，加上可以外接显示器，所有还是偏向于使用小尺寸的。去年购入了一台 Thinkpad 8，由于性能问题并不满意。所以想买一台性能强一点的，看了一下 Sureface 3，除了性能，基本满意，特别是使用手写笔阅读 Pdf 的使用场景，比较符合我的使用需求。

现在也就等本月26日发布会，系统会推出 Surface 4！如果不出，那就纠结了，Surface Pro 4 m3 版本不知道如何，因为模具问题，有散热孔，感觉还是心里有坎~

**Comment by 6101** [comment]
表示买不起  诺基亚还能在坚持几年

**Comment by eoxo** [comment]
好奇最后买了Surface没？？哈哈哈

**Comment by YCF** [comment]
@eoxo 然而并没有，哈哈。

**Comment by eoxo** [comment]
Blog写的还不错呀，咋不更了啊

**Comment by YCF** [comment]
@eoxo 会更的，可能会换静态引擎。
