### ISSUE TITLE
手账入坑：Bullet Journal

### ISSUE THREAD

**Issue by YCF** [YCF/ycf.github.com#24]
手账，其实是日语的说法，其实就是我们常说的：笔记本。

之前有了解和尝试过，是基于A6活页本的方式，采用的是方格内页，因为人懒和没找到比较好的内页布局，所以没怎么做。之前找到记笔记比较好的方式是“康奈尔笔记法”，但始终模式还是太过于固定，记起来没什么新意，也就没什么动力整理笔记。

直到我发现了一种自由漂亮的方式：Bullet Journal。

bullet journal是一种由国外专业网页设计师Ryder Carroll设计出来的(手帐记录)笔记方法。 既然是设计师设计的，美观度自然是不用多说，但最吸引我的是它只需要一支笔、一把尺(个人认为可选)和一个本子。没有之前的各种定制内页，告别了以往沉闷的笔记版面，最合我心意的其实是只要使用“bujo”等关键字，在 Pinterest 等网站上就能搜索到全球同好的版面，实在是我这种没艺术细胞物种的救星。

**Comment by cheerhan** [comment]
看到以后完全改变了我的工作和记录方式~
