### ISSUE TITLE
新键盘：客制版 Filco minila air

### ISSUE THREAD

**Issue by YCF** [YCF/ycf.github.com#30]
之前购入了一个 ikbc Poker [[blog](https://github.com/YCF/ycf.github.com/issues/21)]，因为是有线键盘，我不打游戏，所以感觉那条尾巴是个累赘，所以就出掉了。

但是机械键盘，那手(bi)感(ge)怎能说不要就不要，现阶段市面上 60% 的蓝牙键盘基本只有两个选择：安妮 和 minila air。前者是国产，国产轴，逼格稍微低了点。后者，大家都知道，有点贵。

机缘巧合，刚好有人在全球工单论坛上说过要做一块蓝牙 GH60 的板子，所以就进群了。群主说是 minila 配列，What ? 
![z-shut-up-and-take-my-money-funny-meme](https://cloud.githubusercontent.com/assets/65446/23899941/3c4530d8-08f2-11e7-816b-0cd8f5ff4a6c.jpeg)

经过等待，终于出了 PCB ，凑齐外壳，轴，键帽。焊了个吧小时，解决了一个地方短路的问题，然后因为键盘使用了低功耗蓝牙，叫BLE，其实我也不懂，简单点就是蓝牙4.0，X220内置的适配器不行，淘宝花了25块（含邮费）买了一个，装上，好了！

因为是客制化版本，所以混轴是必须的：

- 大部分使用了红轴，保证了整体的好手感。

- 需要确认的按键用了青轴（ESC,Backspace,Up,Down,Left,Right）和绿轴（Enter,Space,Lshift）。

刚开始走了误区：Lshift 使用了 黑轴，最后的手感就是：渣手感的红轴大键位！

几张图：
![a076bae6ly1fdpph5rwhpj20np0hsaba](https://cloud.githubusercontent.com/assets/65446/24069724/cedfec90-0be9-11e7-8e30-ce4b1e521277.jpg)

![a076bae6ly1fdpph7m15kj20np0hs0u4](https://cloud.githubusercontent.com/assets/65446/24069725/d0a6add4-0be9-11e7-8ee8-6ade256b6669.jpg)

![a](https://cloud.githubusercontent.com/assets/65446/24069738/2ade44a6-0bea-11e7-8d84-f6a0b70bf5a6.jpg)

**Comment by defp** [comment]
👍

**Comment by onlyice** [comment]
楼主动手能力真强

**Comment by qwwsteppenwolf** [comment]
请问PCB上各个键轴的位置坐标在哪里可以查到？还有就是3U空格的卫星轴在哪里买呢？谢谢楼主指点迷津

**Comment by YCF** [comment]
@direwolfwangzf 1U的距离是19.05，3U用的卫星轴和2U的是一样的。
可以看我其他的帖子，这篇提到的键盘pcb不是我做的，而且功能太弱，出掉了。
