### ISSUE TITLE
物联网窥探-wifi,ble,zigbee

### ISSUE THREAD

**Issue by YCF** [YCF/ycf.github.com#31]
表格生成工具: http://www.tablesgenerator.com

可能有误，欢迎指正。

<table>
  <tr>
    <th></th>
    <th>WIFI</th>
    <th>BLE</th>
    <th>Zigbee</th>
  </tr>
  <tr>
    <td>模块体积</td>
    <td>稍大</td>
    <td>超小</td>
    <td>超小</td>
  </tr>
  <tr>
    <td>功耗</td>
    <td>较高，1W</td>
    <td>超低</td>
    <td>超低</td>
  </tr>
  <tr>
    <td>可休眠</td>
    <td>不能</td>
    <td>可以</td>
    <td>可以</td>
  </tr>
  <tr>
    <td>芯片价格</td>
    <td>100+<br>NodeMcu,10+</td>
    <td>20+</td>
    <td>10+</td>
  </tr>
  <tr>
    <td>联网特点</td>
    <td>通过路由器连入互联网</td>
    <td>不能直接连接互联网<br>不能自组网</td>
    <td>通过一个设备Bridge可接入互联网<br>可多设备自动联成蜂窝网，可靠性高，切换快</td>
  </tr>
  <tr>
    <td>速率</td>
    <td>超高</td>
    <td>较低</td>
    <td>最低</td>
  </tr>
</table>

**Comment by ghost** [comment]
来访=-=

**Comment by RenderCoder** [comment]
Wi-Fi 模块有的有低功耗模式，价格来说 10-50元不等，通讯速度取决于通讯方式，不一定很快。
