### ISSUE TITLE
[微创新] Mitosis - 一个类似于二狗布局的无线分体键盘

### ISSUE THREAD

**Issue by YCF** [YCF/ycf.github.com#34]
原版： [reddit:Wireless + Split + QMK = Mitosis](https://www.reddit.com/r/MechanicalKeyboards/comments/66588f/wireless_split_qmk_mitosis/)

我的：[New build:Mitosis-plus,thank you @reverse_bias](https://www.reddit.com/r/MechanicalKeyboards/comments/6tcctx/new_buildmitosisplusthank_you_reverse_bias/)
我做的一个衍生，分体 Planck。[[photos] The REAL let's split : MY TRIDENT build log](https://www.reddit.com/r/MechanicalKeyboards/comments/6um7eg/photos_the_real_lets_split_my_trident_build_log/)
因为鹦鹉哥要求，就贴几个图吧：
![zutmrvfozo-57eavzok2izhiu6yl620zryy-hq4kepo](https://user-images.githubusercontent.com/65446/35263740-ef1ac696-0054-11e8-9e09-de6a459466f4.jpg)
![0ce91bb723f27fb](https://user-images.githubusercontent.com/65446/35263750-fa6be7a0-0054-11e8-80f0-fc920f7150a3.jpg)
![img_20170618_200410_hht](https://user-images.githubusercontent.com/65446/35263764-0731b654-0055-11e8-8e70-087638fcd1a5.jpg)
![img_20170618_200438_hht](https://user-images.githubusercontent.com/65446/35263765-080ec864-0055-11e8-8834-3c62e4b14639.jpg)
![img_20170618_200508_hht](https://user-images.githubusercontent.com/65446/35263767-0aebe67a-0055-11e8-9226-d19a8f3d8110.jpg)
![-5fb5d8738b9bffaa](https://user-images.githubusercontent.com/65446/35263769-0d86d854-0055-11e8-9e0d-b1fd6c4aec6c.jpg)

老外做的一些(都是在我后面做的，哈哈哈)：
[1](https://www.reddit.com/r/MechanicalKeyboards/comments/726fj2/finished_mitosis_build_p/)
[2](https://www.reddit.com/r/MechanicalKeyboards/comments/7b7kjq/mitosis_love/)
[3](https://www.reddit.com/r/MechanicalKeyboards/comments/7a3oq2/mitosis_penumbra_waffle_kitteh/)
[etc](https://www.reddit.com/r/MechanicalKeyboards/search?q=mitosis&restrict_sr=on)

**Comment by rosedev318** [comment]
Buddy, where's the details?:)
