### ISSUE TITLE
断 舍 离 

### ISSUE THREAD

**Issue by YCF** [YCF/ycf.github.com#48]
---
title: "断 舍 离"
categories: 
 - 极简
date: 2020-02-05 16:12:17
tags: [Minimalism]
slug: hello-minimalism
---

### 购物理念

> We buy things we don't need with money we don't have to impress people we don't like. -出处还在查 

### 物品清单

一般断舍离的开始都是要求列出日常物品清单，列出清单是一个收拾的过程，直视清单，分析自己的需求，通过这个简单实用的方式，能初步触摸到“断”。

### 改变衣服堆放方式

物品少了，收纳也将变得简单。为了让生活更加便利，可以适当学习更优秀的收纳方式（优先学习方法，而不是疯狂购买收纳工具）。

### 卖掉旧书

使用多抓鱼APP，扫码，能卖的卖，不能卖的留着找机会送人。

### 清理合并手机APP

清理：
- **地铁通APP** - `广州地铁plus小程序` or `高德地图`
- **QQ邮箱** - Web端
- **印象笔记** - 已全部导入到 Onenote_
- **地图应用** - 只用高德地图
- **豆瓣电影**  只保留 豆瓣APP
- **知乎日报** - web
- **各种 ToDo**  - 微信小程序
- **游戏** - 还真没时间玩

已清理，需要时再临时装：

- **迅雷** - 需要再临时装
- **途虎养车** - 需要再临时装
- **多抓鱼APP** - 卖完书，提现后删除，需要再装
- **嘉立创手机助手** -好久没下过pcb订单了，查询用web就行了
- **什么值得买** -这个不就是极简生活天敌吗？

重装软件（需进一步思考)
- **华为运动健康** - 高德地图有运动功能能满足跑步，但手环数据还是需要看，思考下把手环也丢了。

目标：
- **知乎** - 有些搜索结果在知乎，然后需要用APP才能看，找到解决方案后删掉。

### 无用物品先冷藏，然后丢，丢，丢

很多人片面理解 `断舍离 = 丢丢丢`，疯狂丢弃后又疯狂回购，入门者在刚开始的时候总是会犯错，我觉得先把计划丢弃物品按丢弃计划（1周、1月、1年）进行分批次冷藏，确实不再动用时再丢弃，应该能更好地避免重大错误。（可能这就叫穷吧？）

**Comment by taoeu** [comment]
哈哈哈，最近也在看断舍离，好巧啊

**Comment by YCF** [comment]
删除手机app
1. 嘉立创手机助手，好久没下过pcb订单了，查询用web就行了。
2. 什么值得买，这个不就是天敌吗？

**Comment by YCF** [comment]
@theeao 哈哈，我看了好几年了，拖延症。
